### PR TITLE
Bug fixes and model version check utils

### PR DESCRIPTION
**Pull request by TonyBotongChu**
### Upgraded transformers from 4.33.2 to 4.38.0
Transformers 4.33.2 is vulnerable to https://github.com/advisories/GHSA-3863-2447-669p, https://github.com/advisories/GHSA-v68g-wm8c-6x7j, https://github.com/advisories/GHSA-37q5-v5qm-c9v8.

### Fixed bug: single.py and stream.py default argument not working
Added `nargs='*'` to fix the argparse `default` parameter.

### Renamed get_prompt parameter
Renamed `input` parameter to raw_jp_text, as `input` shadows python built-in method name.

### Added a new version check tool
Added `is_version_compatible` to compare version strings. This will also fix bugs like version `0.9.2` not recognized as subversion of `0.9`. A new unit test is also added.

### CODE REVIEW

**Comment by kurikomoe** [comment]
I wonder whether baichuan (aka SakuraModel 0.8) can be used under transformers 4.33.2. 
Since most people are using v0.9 under llama.cpp-python or ollama, maybe we can deprecate the v0.8 supports?
@pipixia244

**Review by kurikomoe — APPROVED** [review]
haven't fully tested, but LGTM. 
Merge after we have agreed on how to handle the v0.8.

**Comment by pipixia244** [comment]
> I wonder whether baichuan (aka SakuraModel 0.8) can be used under transformers 4.33.2. Since most people are using v0.9 under llama.cpp-python or ollama, maybe we can deprecate the v0.8 supports? @pipixia244

I think v0.8 and before can be deprecated.

**Comment by TonyBotongChu** [comment]
Hi team, just wanted to check if there’s anything else needed from my side for this PR. Since it’s already been approved, I wanted to follow up in case it might have been overlooked for merging. Thank you!

**Comment by kurikomoe** [comment]
> Hi team, just wanted to check if there’s anything else needed from my side for this PR. Since it’s already been approved, I wanted to follow up in case it might have been overlooked for merging. Thank you!

Your pr is quite good, it's my fault for not having enough time to do a full refactor to deprecate the old v0.8.
I think we can merge the PR first and refactor later since no one is still using v0.8.

**Pull request merged**
